# Generated by Django 5.0.7 on 2024-07-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_is_blocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="auto_reply_delay",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="auto_reply_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
