# Generated by Django 5.0.7 on 2024-07-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_auto_reply_delay_post_auto_reply_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="auto_reply_delay",
            field=models.FloatField(default=0),
        ),
    ]
